# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(456, 346)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.searchFilter = QtWidgets.QLineEdit(self.tab)
        self.searchFilter.setObjectName("searchFilter")
        self.horizontalLayout.addWidget(self.searchFilter)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.infoLabel = QtWidgets.QLabel(self.tab)
        self.infoLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout_5.addWidget(self.infoLabel)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.generalFileCheckbox = QtWidgets.QCheckBox(self.tab)
        self.generalFileCheckbox.setObjectName("generalFileCheckbox")
        self.verticalLayout_6.addWidget(self.generalFileCheckbox)
        self.groupCheckbox = QtWidgets.QCheckBox(self.tab)
        self.groupCheckbox.setObjectName("groupCheckbox")
        self.verticalLayout_6.addWidget(self.groupCheckbox)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.loadButton = QtWidgets.QPushButton(self.tab)
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout_7.addWidget(self.loadButton)
        self.searchButton = QtWidgets.QPushButton(self.tab)
        self.searchButton.setEnabled(False)
        self.searchButton.setObjectName("searchButton")
        self.verticalLayout_7.addWidget(self.searchButton)
        self.clearFilesButton = QtWidgets.QPushButton(self.tab)
        self.clearFilesButton.setEnabled(False)
        self.clearFilesButton.setObjectName("clearFilesButton")
        self.verticalLayout_7.addWidget(self.clearFilesButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.setStretch(1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Париснг расписания"))
        self.label.setText(_translate("MainWindow", "Поиск по:"))
        self.infoLabel.setText(_translate("MainWindow", "Готовность"))
        self.generalFileCheckbox.setText(_translate("MainWindow", "Вывод в общий файл"))
        self.groupCheckbox.setText(_translate("MainWindow", "Объединять группы"))
        self.loadButton.setText(_translate("MainWindow", "Загрузить"))
        self.searchButton.setText(_translate("MainWindow", "Поиск"))
        self.clearFilesButton.setText(_translate("MainWindow", "Очистить файлы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Заочники"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Очники"))
